sudo: false
language: python

install:
  - pip install -r requirements.txt

python:
  - '2.7'
  - '3.6'
  - 'pypy'

script:
  - py.test tests --cov winnowing --durations=10

after_success:
- coveralls
